---
- hosts: all
  become: true
  roles:
    - role: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
        state: present
  tasks:
    - name: cp env
      template:
        src: ./template/.env.redmine.j2
        dest: '{{ ansible_env.HOME }}/.env.redmine'
        mode: '660'
    - name: up redmine
      community.docker.docker_container:
        name: redmine
        image: redmine
        ports: [3000:3000]
        env_file: '{{ ansible_env.HOME }}/.env.redmine'
